replicaCount: 1

image:
  repository: ghcr.io/berriai/litellm-database
  tag: main-stable
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name: litellm-sa

masterkeySecretName: litellm-masterkey
masterkeySecretKey: masterkey

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: "1"
    memory: 3Gi

service:
  type: ClusterIP
  port: 4000

db:
  deployStandalone: true

redis:
  enabled: true

proxy_config:
  model_list:
    - model_name: chat-eco
      litellm_params:
        model: bedrock/eu.anthropic.claude-3-haiku-20240307-v1:0
        aws_region_name: eu-west-3
  general_settings:
    master_key: os.environ/PROXY_MASTER_KEY
